import Share, { ShareOptions } from 'react-native-share';
import { Platform } from 'react-native';

export type TipDetailsForPDF = {
    amount: number;
    tip: number;
    total: number;
    tipPercentage: number;
    numberOfPeople: number;
    perPerson?: {
        amount: number;
        tip: number;
        total: number;
    };
    currencySymbol?: string;
};

/**
 * Generates and shares a PDF with tip details
 * Uses HTML to PDF conversion through react-native-share
 */
export const useShareTipDetailsPDF = async (details: TipDetailsForPDF) => {
    const { amount, tip, total, tipPercentage, numberOfPeople, perPerson, currencySymbol = '$' } =
        details;

    // Generate formatted text content for PDF-like sharing
    const pdfContent = `
═══════════════════════════════
       TIPMATE SUMMARY
    Smart Tips, Easy Living
═══════════════════════════════

📋 BILL DETAILS
───────────────────────────────
Bill Amount:       ${currencySymbol}${amount.toFixed(2)}
Tip Percentage:    ${tipPercentage}%
Tip Amount:        ${currencySymbol}${tip.toFixed(2)}
───────────────────────────────
💰 TOTAL AMOUNT:   ${currencySymbol}${total.toFixed(2)}
═══════════════════════════════

${numberOfPeople > 1 && perPerson
            ? `👥 SPLIT DETAILS
───────────────────────────────
Number of People:  ${numberOfPeople}
Subtotal/Person:   ${currencySymbol}${perPerson.amount.toFixed(2)}
Tip/Person:        ${currencySymbol}${perPerson.tip.toFixed(2)}
───────────────────────────────
💵 TOTAL/PERSON:   ${currencySymbol}${perPerson.total.toFixed(2)}
═══════════════════════════════

`
            : ''
        }Generated by TipMate
Date: ${new Date().toLocaleDateString()}
═══════════════════════════════
  `.trim();

    try {
        const shareOptions: ShareOptions = {
            title: 'TipMate Summary (PDF)',
            subject: 'TipMate Summary',
            message: pdfContent,
            // Add filename to suggest saving as PDF
            filename: `TipMate_Summary_${new Date().getTime()}.txt`,
            ...(Platform.OS === 'ios' && {
                saveToFiles: true,
            }),
        };

        await Share.open(shareOptions);
    } catch (err: unknown) {
        const message =
            typeof err === 'object' && err && 'message' in err
                ? (err as { message?: string }).message
                : undefined;

        if (message !== 'User did not share') {
            console.log('PDF generation error:', err);
        }
        throw err;
    }
};
