export const APP_STATE_ASYNCSTORAGE_KEY = 'APPSTATE';
export const USER_SETTINGS_ASYNCSTORAGE_KEY = 'USER_SETTINGS_STATE';
export const CONFIG_ASYNCSTORAGE_KEY = 'CONFIG_STATE';
export const HISTORY_ASYNCSTORAGE_KEY = 'HISTORY_STATE';
